version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies
      - sudo yum install -y yum-utils
      - sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - sudo yum -y install packer
      - sudo yum install -y python3
      - pip3 install ansible
      - echo Installing Packer Ansible plugin
      - packer plugin install github.com/hashicorp/ansible

  build:
    commands:
      - echo Initializing Packer
      - packer init .
      - packer validate amazon-linux.pkr.hcl
      - packer build amazon-linux.pkr.hcl

artifacts:
  files:
    - '**/*'